site_name: Twin Souls prototype

nav:
    - Home: index.md
    - Gameplay:
        - ğŸ§™ Twin: gameplay/Twin.md
        - ğŸ“Œ Main Mechanic: 
            - â›“ï¸ Link concept: gameplay/main-mechanic/Link-concept.md
            - ğŸ¡ Elements equality wheel: gameplay/main-mechanic/Elements-equality-wheel.md
            - ğŸ”„ Element switching: gameplay/main-mechanic/Element-switching.md
            - ğŸ”ï¸ Fusion & Repression: gameplay/main-mechanic/Fusion-Repression.md
            - âš—ï¸ Elements & effects: gameplay/main-mechanic/Elements-effects.md
            - âš™ï¸ Mechanic demonstration: gameplay/main-mechanic/Mechanic-demonstration.md
            - ğŸï¸ Mechanic scenarios: gameplay/main-mechanic/Mechanic-scenarios.md
        - ğŸ“Œ Combat Mechanics:
            - âš”ï¸ Weapons: gameplay/combat-mechanic/weapons.md
            - ğŸ† Spell kit: gameplay/combat-mechanic/spell-kit.md
        - ğŸ“Œ Pre production:
            - ğŸ“œ Implementation details: gameplay/pre-production/technical.md
            - ğŸ“¦ï¸ Assets: gameplay/pre-production/assets.md
            - ğŸ‘ï¸ Feedbacks: gameplay/pre-production/feedback.md
    - Prototype:
        - Overview: prototype/index.md
        - ğŸƒ Puzzle elements: prototype/puzzle.md
        - Join Area: prototype/join.md
        - Area 1 - Pressure plates: prototype/area1.md
        - Area 2 - Pillars: prototype/area2.md
        - Area 3 - Movement ability: prototype/area3.md
        - Area 4 - Training ground: prototype/area4.md
        - Area 5 - Monster waves: prototype/area5.md
    - Play testing:
        - Overview: playtesting/index.md
        - "Discovery session #1": playtesting/discovery-session1.md 
        - "Discovery session #2": playtesting/discovery-session2.md 
        - Balancing sessions: playtesting/balancing-session.md
    
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png

  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - content.code.annotate

  palette: 
    - schema: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate 
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets